### ISSUE TITLE
[Windows] ArgumentError on line ["465"]

### ISSUE THREAD

**Issue by Razunter** [chriseppstein/sass-globbing#13]
Update v1.1.1 broke SASS Globbing for me:

```
ArgumentError on line ["465"] of W: different prefix: "w:/" and "w:\\xampp/htdocs/pafes-studio.ru-new3/sites/all/themes/pafes_studio/sass"
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-globbing-1.1.1/lib/sass/globbing/importer.rb:60:in `mtime'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:134:in `mtime'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:163:in `block in dependency_updated?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:125:in `each'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:125:in `any?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:81:in `call'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.7/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:85:in `needs_update?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:79:in `block in out_of_date?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:78:in `each'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:78:in `out_of_date?'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/watcher/compiler.rb:20:in `compile'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/watch_project.rb:47:in `perform'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/base.rb:18:in `execute'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/project_base.rb:19:in `execute'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/bin/compass:30:in `block in <top (required)>'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/bin/compass:44:in `call'
  W:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.19/bin/compass:44:in `<top (required)>'
  W:/Ruby193/bin/compass:23:in `load'
  W:/Ruby193/bin/compass:23:in `<main>'
```

**Comment by chriseppstein** [comment]
I think it's fixed in `1.1.3`
